dbip: 47.103.64.182
dbport: 63306
dbname: ujiev22
dbuname: root
dbupass: rootpass


server:
  port: 19010


spring:
  datasource:
    url: jdbc:p6spy:mysql://${dbip}:${dbport}/${dbname}?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: ${dbuname}
    password: ${dbupass}
    driverClassName: com.mysql.cj.jdbc.Driver